version: '3.8'

services: 
  backend:
    image: didier3438/webbilling:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build: 
      context: billers-api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  frontend:
    image: didier3438/mbills:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build: 
      context: m-bills
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
  db:
    build:
       context: .
       dockerfile: db.Dockerfile
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: